version: '3.8'
services:
  php-apache-environment:
    container_name: swagger-try
    build:
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html/
      - swagger-try-composer-cache:/root/.composer/cache/
    networks:
      - swagger-try-network
    ports:
      - 8011:80
networks:
  swagger-try-network:
    driver: bridge
volumes:
  swagger-try-composer-cache:
    driver: local
